### ISSUE TITLE
Build fail on Swift project at Xcode 7

### ISSUE THREAD

**Issue by retsohuang** [truebit/xUnique#24]
```
Uniquify and Sort
Traceback (most recent call last):
  File "/usr/local/bin/xunique", line 9, in <module>
    load_entry_point('xUnique==4.1.2', 'console_scripts', 'xunique')()
  File "/Library/Python/2.7/site-packages/xUnique.py", line 508, in main
    xunique.unique_project()
  File "/Library/Python/2.7/site-packages/xUnique.py", line 158, in unique_project
    self.substitute_old_keys()
  File "/Library/Python/2.7/site-packages/xUnique.py", line 166, in substitute_old_keys
    line = line.decode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
KeyboardInterrupt
Command /bin/sh failed with exit code 1
```

**Comment by truebit** [comment]
From the error log, it seems that you force quit xunique by "ctrl-c" while it running? I cannot see any other problems, please describe the symptoms with more details






—

**Comment by retsohuang** [comment]
No, I run this script via Xcode's run scripts, this will fail after build several times, especially at when I editing Stroybaords (Xcode will build project in the background every time when I made some changes in Storyboard) maybe this cause the force quit?

**Comment by truebit** [comment]
Could you try to run xunique manually in terminal instead of the run script build phase and with `-v` flag, like `xunique -v path/to/your/xcodeproj` and paste the logs when failure occurs? I suspect that Xcode hid some error details.
BTW, Isn't the run-script-build-phase done after the build phase? I do not think that's a good time to modify your project file

**Comment by retsohuang** [comment]
Here is the log
https://www.dropbox.com/s/krink8g5zvyzwzu/debug_result.json?dl=0

**Comment by truebit** [comment]
Thanks. please also paste the full terminal output for reference.

**Comment by retsohuang** [comment]
Sorry terminal crashed :(, I'll post when it happen again.

**Comment by truebit** [comment]
OK.
As you said "Xcode will build project in the background every time when I made some changes in Storyboard", I suspect that because of that, Xcode will force quit ongoing building process when you change the storyboard frequently; and when the ongoing process is in "RunScriptBuildPhase", Xcode will force-quit it, the you got that error.

All above is my suspection. If you found anything, please comment here.
Based on my theory, I suggest you use xunique in git hook instead of target shell script phase or scheme pre/post-actions

**Comment by retsohuang** [comment]
I tried that before, but I get following error
```
.git/hooks/pre-commit: line 2: xunique: command not found
```

**Comment by truebit** [comment]
is `/usr/local/bin` in your `PATH` ? `xunique` should be installed in that directory.

**Comment by retsohuang** [comment]
It works now, thanks.
